server:
  port: 9008
spring:
  application:
    name: tensquare-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.189.50:3306/tensquare_user?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: 39.105.189.50
  rabbitmq:
    host: 39.105.189.50
jwt:
  config:
    key: bingo
    ttl: 3600000
