server: 
  port: 9005
spring: 
  application:  
    name: tensquare-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.189.50:3306/tensquare_gathering?characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
